name: My First Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check files exist
        run: |
          echo "Checking repo files..."
          ls
          echo "All files listed successfully, Yusuf!"
      